{
    'name': 'Petty Cash Management',
    'version': '18.0.1.1.0',
    'author': 'Kinan',
    'website': 'absar-alomran.com',
    'category': 'Accounting',
    'summary': 'Manage petty cash expenses with approval workflow and draft journal entry creation.',
    'description': '\n        Petty Cash Management Module\n        ============================\n\n        A complete petty cash management  solution designed for internal accounting teams.\n        This module provides a structured workflow for recording petty cash expenses, \n        submitting them for approval, validating them by accountants, and generating \n        draft journal entries directly into the accounting system.\n\n        Key Features\n        ------------\n        - Petty Cash Reports with automatic sequence numbers\n        - Multi-line petty cash entries with category, VAT, PO/MR/Invoice references, and descriptions\n        - Automatic VAT calculation (optional per line)\n        - Category-based account mapping for expense accounts\n        - Configurable Petty Cash Account, Input VAT Account, and Accounting Journal\n        - Excel Import Wizard for bulk petty cash entry creation (with template download)\n        - Attachment support for each petty cash line and full movement of attachments to journal entries\n        - Approval workflow:\n            • Draft → Submitted (Users)\n            • Submitted → Approved / Rejected (Accountants)\n            • Approved → Reset to Draft\n        - Draft Journal Entry generation with correct debit/credit logic\n        - PDF Printout formatted like existing company request forms\n        - Chatter integration for comments and tracking\n        - Security groups for Users and Accountants\n        - Footer totals for untaxed amount, VAT, and total amount\n\n        This module is fully standalone (backend only). If you also use Employee\n        Portal Suite and want employees to submit/view petty cash reports from the\n        employee portal, the included portal bridge activates automatically when both modules are available.\n        ',
    'depends': ['base', 'account', 'mail', 'web'],
    'data': ['security/security.xml', 'security/ir.model.access.csv', 'data/petty_cash_sequence.xml', 'reports/petty_cash_report_action.xml', 'reports/petty_cash_report_templates.xml', 'views/petty_cash_category_views.xml', 'views/petty_cash_line_views.xml', 'views/petty_cash_views.xml', 'views/res_config_settings_views.xml', 'views/menus.xml', 'wizard/petty_cash_import_wizard_views.xml'],
    'images': ['images/main_screenshot.png'],
    'license': 'OPL-1',
    'price': 24.99,
    'currency': 'USD',
    'installable': True,
    'application': True,
}
